//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cooperativa_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUENTA()
        {
            this.CREDITO = new HashSet<CREDITO>();
            this.TRANSACCION = new HashSet<TRANSACCION>();
        }
    
        public int CuentaID { get; set; }
        public int SocioID { get; set; }
        public bool CuentaActiva { get; set; }
        public string CuentaNotas { get; set; }
        public Nullable<decimal> CuentaSaldo { get; set; }
        public Nullable<System.DateTime> CuentaFechaRegistro { get; set; }
        public Nullable<System.DateTime> CuentaFechaBaja { get; set; }
        public Nullable<int> UsuarioIDRegistra { get; set; }
        public Nullable<int> UsuarioIDBaja { get; set; }
        public int SucursalID { get; set; }
        public string TipoCuentaID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CREDITO> CREDITO { get; set; }
        public virtual SOCIO SOCIO { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
        public virtual TIPO_CUENTA TIPO_CUENTA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACCION> TRANSACCION { get; set; }
    }
}
