//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cooperativa_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_CREDITO
    {
        public int DetalleCreditoID { get; set; }
        public int CreditoID { get; set; }
        public int DetalleCreditoNumeroCuota { get; set; }
        public System.DateTime DetalleCreditoFechaPago { get; set; }
        public System.DateTime DetalleCreditoFechaPagoEsperado { get; set; }
        public decimal DetalleCreditoMonto { get; set; }
        public decimal DetalleCreditoInteres { get; set; }
        public decimal DetalleCreditoInteresMora { get; set; }
        public int DetalleUsuarioCobra { get; set; }
        public decimal DetalleCapitalAmortizado { get; set; }
        public string DetalleCreditoNotas { get; set; }
    
        public virtual CREDITO CREDITO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
