//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cooperativa_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public int PersonaID { get; set; }
        public bool EmpleadoEstado { get; set; }
        public System.DateTime EmpleadoFechaRegistro { get; set; }
        public Nullable<System.DateTime> EmpleadoFechaBaja { get; set; }
        public string EmpleadoNotas { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
