//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cooperativa_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOCIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOCIO()
        {
            this.CUENTA = new HashSet<CUENTA>();
        }
    
        public int PersonaID { get; set; }
        public bool SocioActivo { get; set; }
        public System.DateTime SocioFechaRegistro { get; set; }
        public Nullable<System.DateTime> SocioFechaBaja { get; set; }
        public string SocioNotas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUENTA> CUENTA { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
