//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cooperativa_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACCION
    {
        public long TransaccionID { get; set; }
        public int TransaccionCuentaID { get; set; }
        public System.DateTime TransaccionFecha { get; set; }
        public decimal TransaccionMonto { get; set; }
        public bool TransaccionActiva { get; set; }
        public string TipoTransaccionID { get; set; }
        public int TransaccionUsuarioRegistraID { get; set; }
        public int TransaccionSucursalID { get; set; }
    
        public virtual CUENTA CUENTA { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
        public virtual TIPO_TRANSACCION TIPO_TRANSACCION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
