//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cooperativa_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.CREDITO = new HashSet<CREDITO>();
            this.CUENTA = new HashSet<CUENTA>();
            this.CUENTA1 = new HashSet<CUENTA>();
            this.DETALLE_CREDITO = new HashSet<DETALLE_CREDITO>();
            this.TRANSACCION = new HashSet<TRANSACCION>();
        }
    
        public int PersonaID { get; set; }
        public string UsuarioID { get; set; }
        public string UsuarioPassword { get; set; }
        public bool UsuarioActivo { get; set; }
        public string UsuarioNotas { get; set; }
        public Nullable<bool> UsuarioDiscapacidad { get; set; }
        public Nullable<bool> UsuarioPermisoChat { get; set; }
        public Nullable<bool> UsuarioPermisoRecargas { get; set; }
        public Nullable<bool> UsuarioPermisoGestionarCuentas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CREDITO> CREDITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUENTA> CUENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUENTA> CUENTA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_CREDITO> DETALLE_CREDITO { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACCION> TRANSACCION { get; set; }
    }
}
